services:

  postgres:
      image: postgres:15
      environment:
        POSTGRES_DB: corporate_banking
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      networks:
        - banknet


  kafka:
    image: apache/kafka:4.0.1-rc2
    ports:
      - "9092:9092"
    networks:
      - banknet
    environment:
      # These environment variables are formatted for the apache/kafka image
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://kafka:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      # The image will generate a cluster ID on its own if not provided
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list" ]
      interval: 10s
      timeout: 5s
      retries: 5

  transaction-service:
    build: ../transaction-service
    networks:
      - banknet
    ports:
      - "1001:1001"
      - "9095:9095"
    environment:
      - DB_URL=${CORPORATE_DB_URL}
      - DB_USERNAME=${CORPORATE_DB_USERNAME}
      - DB_PASSWORD=${CORPORATE_DB_PASSWORD}
  faq-service:
    build: ../faq-service
    networks:
      - banknet
    ports:
      - "2001:2001"
      - "9094:9094"
    environment:
      - DB_URL=${CORPORATE_DB_URL}
      - DB_USERNAME=${CORPORATE_DB_USERNAME}
      - DB_PASSWORD=${CORPORATE_DB_PASSWORD}
    depends_on:
      - postgres

  nrc-service:
    build: ../nrc-service
    networks:
      - banknet
    ports:
      - "3002:3002"
      - "9093:9093"
    environment:
      - DB_URL=${CORPORATE_DB_URL}
      - DB_USERNAME=${CORPORATE_DB_USERNAME}
      - DB_PASSWORD=${CORPORATE_DB_PASSWORD}

  user-service:
    build: ../user-service
    depends_on:
      kafka:
        condition: service_healthy
      nrc-service:
        condition: service_started
    networks:
      - banknet
    ports:
      - "3001:3001"
      - "9091:9091"
    environment:
      - DB_URL=${CORPORATE_DB_URL}
      - DB_USERNAME=${CORPORATE_DB_USERNAME}
      - DB_PASSWORD=${CORPORATE_DB_PASSWORD}

  mail-service:
    build: ../mail-service
    networks:
      - banknet
    ports:
      - "7000:7000"

  upload-service:
    build: ../upload-service
    networks:
      - banknet
    ports:
      - "8001:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_OWNER=${GITHUB_OWNER}
      - GITHUB_REPO=${GITHUB_REPO}
      - GITHUB_TARGET_FOLDER=${GITHUB_TARGET_FOLDER}

  auth-service:
    build: ../auth-service
    networks:
      - banknet
    ports:
      - "9999:9999"
    environment:
      - DB_URL=${CORPORATE_DB_URL}
      - DB_USERNAME=${CORPORATE_DB_USERNAME}
      - DB_PASSWORD=${CORPORATE_DB_PASSWORD}

  gateway-service:
    build: ../gateway-service
    depends_on:
      user-service:
        condition: service_started
      faq-service:
        condition: service_started
      transaction-service:
        condition: service_started
      auth-service:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - banknet
    ports:
      - "8080:8080"

networks:
  banknet:
    driver: bridge
