server:
  port: 3001

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

grpc:
  server:
    port: 9091
  client:
    nrc-service:
      address: "static://nrc-service:9093"
      negotiation-type: plaintext
